// UA Thesis Template in Markdown
// Autor: João Paulo Barraca

#import "ua-thesis-template.typ": ua-thesis

// 1. Initialize the Template
#show: ua-thesis.with(
  title-pt: "Title PT",
  title-en: "Title EN",
  author: "Author Name",
  year: "2026",
  degree: "Mestrado em X",
  department: "DEPARTAMENTO",
  logo: "figs/ua-logo.png",
  
  supervisors: (
    "Prof. Dr. A", 
    "Prof. Dra. B"
  ),
  
  jury: (
    (role: "Presidente", name: "Prof. Dr. A", title: "Professor Catedrático da Universidade de Aveiro"),
    (role: "Vogal", name: "Prof. Dr. B", title: "Professor Associado da X"),
    (role: "Orientador", name: "Prof. Dr. A", title: "Professor Auxiliar da Universidade de Aveiro")
  ),

  grant-text: [
    Text: Apoio financeiro do POCTI no âmbito do III Quadro Comunitário de Apoio.
    (if applicable- Portuguese mandatory)
  ],

  acknowledgements: [
    Gostaria de expressar a minha profunda gratidão aos meus orientadores e à Universidade de Aveiro 
    por todo o apoio prestado durante a elaboração desta dissertação. 
    O meu muito obrigado à minha família e amigos pelo suporte constante.
  ],

  keywords-pt: ("Typst", "Tese", "Universidade de Aveiro"),
  abstract-pt: [
    Text
  ],

  keywords-en: ("Typst", "Thesis", "University of Aveiro"),
  abstract-en: [
    Text
  ],

  dedication: [ Dedication (Optional)],

  ai-acknowledgement: [
     I acknowledge the use of [insert AI system(s) and link] to [specific use of generative artificial intelligence or other tasks]. I acknowledge the use of [software, codes or platforms] to [specific use software, codes or platforms or to other tasks].

      Example 1: I acknowledge the use of ChatGPT 3.5 (Open AI, https://chat.openai.com) to summarise the initial notes and to proofread the final draft and the use of Office365 (Microsoft, https://www.office.com) for text writing and productivity.

      Example 2: No content generated by AI technologies has been used in this Thesis.
  ]
)

// -----------------------------------------------------------------------------
// 2. Main Content Starts Here
// -----------------------------------------------------------------------------

= Introdução
A Universidade de Aveiro (UA) possui diretrizes específicas de formatação gráfica para dissertações de mestrado e teses de doutoramento. 

== Motivação
A escrita de uma tese não deve ser atrasada por erros enigmáticos de compilação ou incompatibilidade de pacotes. 
O Typst utiliza conceitos inspirados no Markdown, permitindo que o foco permaneça inteiramente na pesquisa científica.


= Conclusão
O Typst demonstrou ser extremamente capaz de replicar a estrutura complexa da capa, folha de rosto e páginas de metadados exigidas pelas normas da Universidade de Aveiro, mantendo o ficheiro de template num formato facilmente legível em comparação com a tradicional complexidade de um ficheiro `.sty`.
